# Generated by Django 4.2.2 on 2023-07-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0003_membership_userprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Athena.membership'),
        ),
    ]
