# Generated by Django 4.2.2 on 2023-07-02 21:37

import Athena.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0004_user_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofiles',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='img',
            field=models.ImageField(upload_to=Athena.models.user_directory_path),
        ),
    ]
