# Generated by Django 4.2.2 on 2023-07-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0007_coursecategories_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategories',
            options={'ordering': ['category']},
        ),
    ]
