# Generated by Django 4.2.2 on 2023-07-08 04:08

import Athena.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0009_course_course_difficulty_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_banner',
            field=models.ImageField(default='Athena/media/course_banner.jpg', upload_to=Athena.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
