# Generated by Django 4.2.2 on 2023-07-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0012_alter_course_course_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_day',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
