# Generated by Django 4.2.2 on 2023-07-11 03:36

import Athena.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0014_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=Athena.models.course_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('visibility', models.BooleanField(default=True)),
                ('is_streaming', models.BooleanField(default=False)),
                ('video_file', models.FileField(blank=True, upload_to=Athena.models.course_directory_path)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Athena.course')),
                ('files', models.ManyToManyField(blank=True, to='Athena.file')),
            ],
        ),
    ]
