# Generated by Django 4.2.1 on 2023-07-18 07:36

import Athena.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0015_file_coursechapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('visibility', models.BooleanField(default=True)),
                ('time', models.PositiveIntegerField()),
                ('each_mark', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('negative_marking', models.BooleanField(default=False)),
                ('negative_grade', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('instructions', models.TextField(max_length=1024)),
                ('files', models.FileField(blank=True, upload_to=Athena.models.course_directory_path)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Athena.course')),
            ],
        ),
    ]
