# Generated by Django 4.2.2 on 2023-07-17 23:05

import Athena.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0016_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='files',
            field=models.FileField(blank=True, upload_to=Athena.models.course_directory_path),
        ),
    ]
