# Generated by Django 4.2.1 on 2023-07-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0016_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('options_1', models.CharField(max_length=256)),
                ('options_2', models.CharField(max_length=256)),
                ('options_3', models.CharField(max_length=256)),
                ('options_4', models.CharField(max_length=256)),
                ('answers', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Athena.course')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Athena.quiz')),
            ],
        ),
    ]
