# Generated by Django 4.2.2 on 2023-07-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0020_remove_studentquizsubmission_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='each_mark',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
