# Generated by Django 4.2.2 on 2023-07-19 09:14

import Athena.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0021_quiz_each_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursechapter',
            name='files',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='files',
            field=models.FileField(blank=True, upload_to=Athena.models.course_directory_path),
        ),
    ]
