# Generated by Django 4.2.2 on 2023-07-20 14:24

import Athena.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0022_remove_coursechapter_files_delete_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to=Athena.models.course_directory_path)),
                ('instructions', models.TextField(max_length=1024)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('deadline', models.DateTimeField()),
                ('plagiarism_check', models.BooleanField(default=False)),
                ('visibility', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Athena.course')),
            ],
        ),
    ]
