# Generated by Django 4.2.2 on 2023-07-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0023_courseassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInPersonExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('exam_date', models.DateTimeField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Athena.course')),
            ],
        ),
    ]
